config/routes.rb
Rails.application.routes.draw do
  root "teams#index"

  resources :users do
    resources :teams, shallow:true
  end
  resources :superheros

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/logout", to: "users#logout"
  get "/login", to: "users#login"
  post "/login", to:"users#attempt_login"
end

app/models/nasa.rb
class Nasa < ActiveRecord::Base
  belongs_to :team
  belongs_to :superhero
end

app/models/superhero.rb
class Superhero < ActiveRecord::Base
  validates :name, :height, :bio, :image_url, presence: true
  has_many :teams, through: :nasas
  has_many :nasas, dependent: :destroy
end

app/models/team.rb
class Team < ActiveRecord::Base
  validates :name, :description, presence: true
  belongs_to :user
  has_many :superheros, through: :nasas
  has_many :nasas, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true, uniqueness: true
  has_many :teams, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def confirm_logged_in
    unless session[:user_id]
      redirect_to login_path, alert: "Please log in!"
    end
  end

  def prevent_login_signup
    if session[:user_id]
      redirect_to "/", notice: "You are already logged in!"
    end
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def admin_user
    return unless session[:is_admin]
    @admin_user ||= User.find_by_id(session[:is_admin])
  end

  helper_method :current_user, :admin_user
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  before_action :current_user
  before_action :admin_user, only: [:index, :show, :new, :edit]
  before_action :find_one, only: [:show, :edit, :update, :destroy]

  def index
    @superheros = Superhero.all
  end

  def new
    @superhero = Superhero.new
  end

  def create
    @superhero = Superhero.new superhero_params
    if @superhero.save
      redirect_to superheros_path
    else
      render :new
    end
  end

  def show
    @teams = Team.all
  end

  def edit
    @teams = Team.all
  end

  def update
    if @superhero.update superhero_params
      redirect_to superheros_path
    else
      render :edit
    end
  end

  def destroy
    @superhero.destroy
    redirect_to superheros_path
  end

  private

    def find_one
      @superhero = Superhero.find params[:id]
    end

    def superhero_params
      params.require(:superhero).permit(:name, :height, :bio, :image_url, :team_ids => [])
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :find_team, only:[:show]
  before_action :current_user
  before_action :confirm_logged_in, only: [:new]
  before_action :find_user, only: [:new]

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new team_params
    if @team.save
      redirect_to "/", notice: "Team successfully created!"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  private

    def team_params
      params.require(:team).permit(:name, :description)
    end

    def find_team
      @team = Team.find params[:id]
    end

    def find_user
      @user = User.find params[:user_id]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user
  before_action :prevent_login_signup, only: [:signup, :login]

  def index
  end

  def new
     @user = User.new
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/", notice: "User created!"
    else
      render :new
    end
  end

  def login
  end

  def attempt_login
    if params[:username].present? && params[:password].present?
      found_user = User.where(username:params[:username]).first
      if found_user
        if found_user.is_admin
          admin_user = found_user.authenticate(params[:password])
        else
          authorized_user = found_user.authenticate(params[:password])
        end
      end
    end

  if admin_user
    session[:user_id] = admin_user.id
    session[:is_admin] = admin_user.id
  end

  if !found_user
    flash.now[:alert] = "Invalid username"
    render :login

  elsif !authorized_user && !admin_user
    flash.now[:alert] = "Invalid password"
    render :login

  else
    if !admin_user
      session[:user_id] = authorized_user.id
    end
    flash[:notice] = "You are now logged in."
    redirect_to "/"
  end

end


  def logout
    session[:user_id] = nil
    session[:is_admin] = nil
    redirect_to "/", notice: "You've sucessfully logged out!"
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_digest, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheros</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/superheros/_checkform.html.erb
<%= form_for superhero do |f| %>
  <%= f.collection_check_boxes(:team_ids, @teams, :id, :name) do |b| %>
    <span>
      <%= b.check_box %>
      <%= b.label %>
    </span>
  <% end  %>
<% end %>

app/views/superheros/_form.html.erb
<div class="col-md-8 col-md-offset-2 text-center">
  <% @superhero.errors.full_messages.each do |e| %>
    <h2><span class="label label-danger"><%= e %></span></h2>
  <% end %><br>
  <%= form_for @superhero do |f| %>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "name:" %>
    <%= f.text_field :name, class: "form-control" %>  
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "height:" %>
    <%= f.text_field :height, class: "form-control" %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "bio: " %>
    <%= f.text_field :bio, class: "form-control" %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "image url: " %>
    <%= f.text_field :image_url, class: "form-control" %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
   <%= f.collection_check_boxes(:team_ids, @teams, :id, :name) do |b| %>
       <span>
         <%= b.check_box %>
         <%= b.label %>
       </span>
     <% end  %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.submit class: "form-control btn btn-primary" %>
   </div>
  <% end %>
</div>

app/views/superheros/_navbar.html.erb
<% unless @current_user %>
  <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/signup">Sign Up <span class="sr-only">(current)</span></a></li>
        <li><a href="/login">Log in <span class="sr-only">(current)</span></a></li>
      </ul>
  </div>
</nav>
<% else %>
  <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><h4><strong>Welcome back <%= @current_user.username %>!</strong></h4></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><input type="button" class="btn btn-default" onclick="location.href='/logout'" value="Log Out"><span class="sr-only">(current)</span></li>
        <li><button class="btn btn-default"><%= link_to "New TEAM", new_user_team_path(@current_user) %></button>   <span class="sr-only">(current)</span></li>
      </ul>
  </div>
</nav>
<% end -%>

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-sucess" %>
  <% end %>
<% end %>

app/views/superheros/edit.html.erb
<%= render "navbar" %>
<h1 class="text-center">Edit <%= @superhero.name %></h1>
<%= render "form" %>

app/views/superheros/index.html.erb
<%= render 'navbar' %>

<div class="text-center">
<h1><p class="glyphicon glyphicon-star"></p>All Superheros<p class="glyphicon glyphicon-star"></p><br></h1> <% if @admin_user %>
  <%= link_to "Add a new Superhero", new_superhero_path %>
<% end %> 
<div>
<br>

<% @superheros.each do |superhero| %>
  <div class="col-md-4">
    <div class="jumbotron text-center">
      <h3><strong><%= superhero.name %><strong></h3>
     <%= link_to "View", superhero_path(superhero)%>
      <hr>
      <img src="<%= superhero.image_url %> " width: "400px", height="200px">
      <p>Height: "<%= superhero.height %>"</i></p>
      <p><i>"<%= superhero.bio %>"</i></p><br>
      <a href="/"><button class="btn btn-info">Home</button></a>
    </div>    
  </div>
<% end %>

app/views/superheros/new.html.erb
<h1 class="text-center">New Superhero</h1><hr>
<%= render "form" %>

app/views/superheros/show.html.erb
<%= render "navbar" %>
<div class="col-md-4">
  <div class="jumbotron text-center">
    <h3><strong><%= @superhero.name %><strong></h3>
    <% if @current_user %>
      <%= render partial: "checkform", locals:{superhero: @superhero} %>
    <% end %><hr>
    <img src="<%= @superhero.image_url %> " width: "400px", height="200px">
    <p>Height: "<%= @superhero.height %>"</i></p>
    <p><i>"<%= @superhero.bio %>"</i></p><br>
    <a href="/"><button class="btn btn-info">Home</button></a>
    <a href="/superheros"><button class="btn btn-info">Back</button>
    </a><br><br>
    <% if @admin_user %>
    <%= link_to "Edit this Superhero", edit_superhero_path  %> <br>
    <%= link_to "Delete this Superhero", superhero_path(@superhero), method: "delete", data:{alert:"Are you Sure?"}  %>
    <% end %>
  </div>    
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login.html.erb
<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-sucess" %>
  <% end %>
<% end %>

<h1 class="text-center">LOG IN</h1><hr>
<div class="col-md-8 col-md-offset-2 text-center">
  <%= form_tag login_path do %>
   <div class="col-md-4 col-md-offset-4">
    <%= label_tag "username:" %>
    <%= text_field_tag :username, params[:username], autofocus: true %>  
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= label_tag "password:" %>
    <%= password_field_tag :password%>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= submit_tag "log in",class: "btn btn-primary" %>
   </div><br>
    <%= link_to "Don't have an account? Sign up here", signup_path %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">SIGN YOU UP in 2 seconds!</h1><hr>
<div class="col-md-8 col-md-offset-2 text-center">
  <% @user.errors.full_messages.each do |e| %>
    <h2><span class="label label-danger"><%= e %></span></h2>
  <% end %><br>
  <%= form_for @user do |f| %>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "username:" %>
    <%= f.text_field :username, class: "form-control" %>  
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "password:" %>
    <%= f.password_field :password, class: "form-control" %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.label "Confirm Password: " %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
   </div><br>
   <div class="col-md-4 col-md-offset-4">
    <%= f.submit "sign up",class: "form-control btn btn-primary" %>
   </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>